server:
  ip: 127.0.0.1
  image:
    name: image
    path: 'C:\just-for-you\UploadFile\${server.image.name}\'
  file:
    name: file
    path: 'C:\just-for-you\UploadFile\${server.file.name}\'
  summary-token:
    value: ''
  emotion-token:
    value: ''
  topic-token:
    value: ''
logging:
  level:
    sqltiming: DEBUG
    resultsettable: DEBUG
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
